# Nombre del teclado (Bluetooth)
CONFIG_ZMK_KEYBOARD_NAME="Hector Corne W"

# Combos
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=5

# Mouse / Pointing
CONFIG_ZMK_POINTING=y

# Battery reporting
CONFIG_ZMK_BATTERY_REPORTING=y

# Split keyboard battery sync (recomendado mantener)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Mejora conexiones BLE (especialmente en clones)
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5